<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-0BGE448" failures="3" tests="5" name="Test" time="21.062" errors="0" timestamp="30 Jan 2022 03:35:14 GMT">
  <testcase classname="TestCases.AddPayeeDatadriven" name="login" time="3.44"/>
  <testcase classname="TestCases.AddPayeeDatadriven" name="addPayee" time="2.45"/>
  <testcase classname="TestCases.AddPayeeDatadriven" name="addPayee" time="0.986">
    <failure type="java.lang.AssertionError" message="expected [The new payee Payee1 was successfully created.] but found [The new payee Payee2 was successfully created.]">
      <![CDATA[java.lang.AssertionError: expected [The new payee Payee1 was successfully created.] but found [The new payee Payee2 was successfully created.]
	at TestCases.AddPayeeDatadriven.addPayee(AddPayeeDatadriven.java:83)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- addPayee -->
  <testcase classname="TestCases.AddPayeeDatadriven" name="addPayee" time="1.448">
    <failure type="java.lang.AssertionError" message="expected [The new payee Payee1 was successfully created.] but found [The new payee Payee3 was successfully created.]">
      <![CDATA[java.lang.AssertionError: expected [The new payee Payee1 was successfully created.] but found [The new payee Payee3 was successfully created.]
	at TestCases.AddPayeeDatadriven.addPayee(AddPayeeDatadriven.java:83)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- addPayee -->
  <testcase classname="TestCases.AddPayeeDatadriven" name="addPayee" time="0.962">
    <failure type="java.lang.AssertionError" message="expected [The new payee Payee1 was successfully created.] but found [The new payee Payee4 was successfully created.]">
      <![CDATA[java.lang.AssertionError: expected [The new payee Payee1 was successfully created.] but found [The new payee Payee4 was successfully created.]
	at TestCases.AddPayeeDatadriven.addPayee(AddPayeeDatadriven.java:83)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- addPayee -->
</testsuite> <!-- Test -->
